// Permission codes (mirrors public.permissions). UI visibility uses these,
// but every server action re-checks them and RLS enforces them in the DB.
export const P = {
  patientsView: "patients.view",
  patientsViewAll: "patients.view_all",
  patientsCreate: "patients.create",
  patientsEdit: "patients.edit",
  patientsArchive: "patients.archive",
  allergyView: "allergy.view",
  medicalView: "medical_history.view",
  medicalEdit: "medical_history.edit",
  investigationsView: "investigations.view",
  investigationsEdit: "investigations.edit",
  visitsView: "visits.view",
  visitsViewRecent: "visits.view_recent",
  visitsCreate: "visits.create",
  visitsEdit: "visits.edit",
  visitsComplete: "visits.complete",
  visitsEditCompleted: "visits.edit_completed",
  fertilityView: "fertility.view",
  fertilityEdit: "fertility.edit",
  oiView: "oi.view",
  oiEdit: "oi.edit",
  pregnancyView: "pregnancy.view",
  pregnancyEdit: "pregnancy.edit",
  gynecologyView: "gynecology.view",
  gynecologyEdit: "gynecology.edit",
  documentsView: "documents.view",
  documentsUpload: "documents.upload",
  documentsArchive: "documents.archive",
  appointmentsView: "appointments.view",
  appointmentsViewHistory: "appointments.view_history",
  appointmentsCreate: "appointments.create",
  appointmentsEdit: "appointments.edit",
  appointmentsCancel: "appointments.cancel",
  appointmentsCheckin: "appointments.checkin",
  appointmentsReminders: "appointments.reminders",
  settingsManage: "settings.manage",
  usersManage: "users.manage",
  rolesManage: "roles.manage",
  auditView: "audit.view",
  settingsEmailView: "settings.email.view",
  settingsEmailManage: "settings.email.manage",
  notificationsView: "notifications.view",
  notificationsManage: "notifications.manage",
  templatesView: "templates.view",
  templatesCreate: "templates.create",
  templatesEdit: "templates.edit",
  templatesDelete: "templates.delete",
  messagesSend: "messages.send",
  messagesSendEmail: "messages.send_email",
  messagesPrepareWhatsapp: "messages.prepare_whatsapp",
  securityView: "security.view",
  securityManage: "security.manage",
  sessionsView: "sessions.view",
  sessionsRevoke: "sessions.revoke",
  documentsGenerate: "documents.generate",
  documentsShare: "documents.share",
  documentsDelete: "documents.delete",
  accountingView: "accounting.view",
  accountingCreate: "accounting.create",
  accountingEdit: "accounting.edit",
  accountingRefund: "accounting.refund",
  accountingDiscount: "accounting.discount",
  accountingCloseDay: "accounting.close_day",
  pricingView: "pricing.view",
  pricingManage: "pricing.manage",
  reportsView: "reports.view",
  reportsCreate: "reports.create",
  reportsEdit: "reports.edit",
  reportsDelete: "reports.delete",
  prescriptionsView: "prescriptions.view",
  prescriptionsCreate: "prescriptions.create",
  prescriptionsEdit: "prescriptions.edit",
  medicationsManage: "medications.manage",
  drawingsView: "drawings.view",
  drawingsCreate: "drawings.create",
  drawingsEdit: "drawings.edit",
} as const

export type PermissionCode = (typeof P)[keyof typeof P]

export type PermissionSet = ReadonlySet<string>

export const can = (perms: PermissionSet, code: PermissionCode) => perms.has(code)
export const canAny = (perms: PermissionSet, ...codes: PermissionCode[]) => codes.some((c) => perms.has(c))
